app:
  handler: dist/app.handler
  timeout: ${env:AWS_LAMBDA_TIMEOUT_SECONDS}
  events:
    - httpApi:
        method: 'GET'
        path: /{any+}
    - httpApi:
        method: 'POST'
        path: /{any+}
    - httpApi:
        method: 'PUT'
        path: /{any+}
    - httpApi:
        method: 'DELETE'
        path: /{any+}
