Resources:
  PdfBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.AWS_S3_PDF_BUCKET}
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: ['GET']
            AllowedOrigins: ['*']
  PdfBucketPermissions:
    Type: AWS::S3::BucketPolicy
    DependsOn: PdfBucket
    Properties:
      Bucket: ${self:provider.environment.AWS_S3_PDF_BUCKET}
      PolicyDocument:
        Statement:
          - Principal: '*'
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetObject
              - s3:ListBucket
            Effect: Allow
            Sid: 'AddPerm'
            Resource:
              - arn:aws:s3:::${self:provider.environment.AWS_S3_PDF_BUCKET}
              - arn:aws:s3:::${self:provider.environment.AWS_S3_PDF_BUCKET}/*
  TeamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.TEAMS_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: leagueId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.LEAGUE_ID_INDEX}
          KeySchema:
            - AttributeName: leagueId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.GAMES_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: leagueId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.LEAGUE_ID_INDEX}
          KeySchema:
            - AttributeName: leagueId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  GameEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.GAME_EVENTS_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: leagueId
          AttributeType: S
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ${self:provider.environment.LEAGUE_ID_INDEX}
          KeySchema:
            - AttributeName: leagueId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: ${self:provider.environment.GAME_ID_INDEX}
          KeySchema:
            - AttributeName: gameId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  LeaguesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.LEAGUES_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  PdfsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.PDF_TABLE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
